%% Target 5: Blood Pressure Prediction from PTT
%
% This script predicts blood pressure from a Pulse Transit Time (PTT) value.
%
% The prediction uses the SAME model as target_3_predictive_model.m:
%   delta_BP = intercept + sum(coefficient_i * feature_i)
%   predicted_BP = calibration_BP + delta_BP
%
% Features used by target_3 (4 features):
%   - delta_ptt: PTT change from calibration (computed from user input)
%   - delta_hr: Heart rate change from calibration (default: 0)
%   - ptt_iqr: PTT interquartile range (default: 0 for single value)
%   - cv_ptt: Coefficient of variation (default: 0 for single value)
%
% When only PTT is provided, other features default to 0.
%
% Model coefficients are loaded from target_3_predictive_model.m output.
%
% Author: Elena Cavazza
% Date: 2026

function target_5_demonstration()
    %% Load Model Coefficients from Target 3 Output
    % The model coefficients are generated by target_3_predictive_model.m
    % and saved to output/model_metrics.csv
    
    metrics_path = fullfile('..', 'output', 'model_metrics.csv');
    if ~exist(metrics_path, 'file')
        metrics_path = fullfile('output', 'model_metrics.csv');
    end
    
    if ~exist(metrics_path, 'file')
        fprintf('Error: Model metrics file not found.\n');
        fprintf('Please run target_3_predictive_model.m first to train the model.\n');
        return;
    end
    
    % Load all model coefficients from target_3 output
    metrics = readtable(metrics_path);
    
    % Load intercepts
    sys_intercept = get_metric(metrics, 'sys_intercept');
    dia_intercept = get_metric(metrics, 'dia_intercept');
    
    % Load feature coefficients (same features as target_3)
    sys_coef_delta_ptt = get_metric(metrics, 'sys_coef_delta_ptt');
    sys_coef_delta_hr = get_metric(metrics, 'sys_coef_delta_hr');
    sys_coef_ptt_iqr = get_metric(metrics, 'sys_coef_ptt_iqr');
    sys_coef_cv_ptt = get_metric(metrics, 'sys_coef_cv_ptt');
    
    dia_coef_delta_ptt = get_metric(metrics, 'dia_coef_delta_ptt');
    dia_coef_delta_hr = get_metric(metrics, 'dia_coef_delta_hr');
    dia_coef_ptt_iqr = get_metric(metrics, 'dia_coef_ptt_iqr');
    dia_coef_cv_ptt = get_metric(metrics, 'dia_coef_cv_ptt');
    
    % Check if new format exists, otherwise fall back to old format
    if isnan(sys_intercept)
        % Fall back to old format (ptt_coef_sys, ptt_coef_dia)
        sys_intercept = 0;
        dia_intercept = 0;
        sys_coef_delta_ptt = get_metric(metrics, 'ptt_coef_sys');
        dia_coef_delta_ptt = get_metric(metrics, 'ptt_coef_dia');
        sys_coef_delta_hr = 0;
        dia_coef_delta_hr = 0;
        sys_coef_ptt_iqr = 0;
        dia_coef_ptt_iqr = 0;
        sys_coef_cv_ptt = 0;
        dia_coef_cv_ptt = 0;
        fprintf('Note: Using legacy model format (PTT coefficient only).\n');
        fprintf('Run target_3_predictive_model.m to generate full model.\n\n');
    end
    
    if isnan(sys_coef_delta_ptt) || isnan(dia_coef_delta_ptt)
        fprintf('Error: Could not load model coefficients from %s\n', metrics_path);
        return;
    end
    
    fprintf('Loaded model coefficients from target_3 output:\n');
    fprintf('  Systolic:  intercept=%.4f, delta_ptt=%.4f, delta_hr=%.4f, ptt_iqr=%.4f, cv_ptt=%.4f\n', ...
            sys_intercept, sys_coef_delta_ptt, sys_coef_delta_hr, sys_coef_ptt_iqr, sys_coef_cv_ptt);
    fprintf('  Diastolic: intercept=%.4f, delta_ptt=%.4f, delta_hr=%.4f, ptt_iqr=%.4f, cv_ptt=%.4f\n\n', ...
            dia_intercept, dia_coef_delta_ptt, dia_coef_delta_hr, dia_coef_ptt_iqr, dia_coef_cv_ptt);
    
    %% Population Defaults (computed from training data)
    % Used when user doesn't have calibration values
    DEFAULT_PTT_MS = 380;   % Median PTT in milliseconds
    DEFAULT_SYS = 127;      % Mean systolic BP (mmHg)
    DEFAULT_DIA = 77;       % Mean diastolic BP (mmHg)
    
    % Sampling rate (for converting ms to samples)
    FS = 250;  % Hz
    
    %% Welcome Message
    fprintf('============================================================\n');
    fprintf('Blood Pressure Prediction from Pulse Transit Time (PTT)\n');
    fprintf('============================================================\n\n');
    
    fprintf('This tool predicts blood pressure using the SAME model as target_3.\n');
    fprintf('PTT is the time delay between an ECG R-peak and PPG pulse peak.\n\n');
    
    %% Step 1: Get PTT Value
    fprintf('--- STEP 1: Enter PTT Value ---\n');
    ptt_ms = input('Enter your PTT value in milliseconds (e.g., 350): ');
    
    % Validate input
    if isempty(ptt_ms) || ~isnumeric(ptt_ms) || ptt_ms <= 0
        fprintf('Error: Invalid PTT value. Please enter a positive number.\n');
        return;
    end
    
    % Physiological bounds check
    if ptt_ms < 100 || ptt_ms > 700
        fprintf('Warning: PTT of %.1f ms is outside typical range (100-700 ms).\n', ptt_ms);
        cont = input('Continue anyway? (Y/N): ', 's');
        if ~strcmpi(cont, 'Y')
            fprintf('Aborted.\n');
            return;
        end
    end
    
    fprintf('\n');
    
    %% Step 2: Get Calibration Values (optional)
    fprintf('--- STEP 2: Calibration Values ---\n');
    fprintf('Calibration improves accuracy by using your baseline measurements.\n');
    fprintf('If you don''t have calibration values, population defaults will be used.\n\n');
    
    has_calib = input('Do you have calibration BP values? (Y/N): ', 's');
    
    if strcmpi(has_calib, 'Y')
        fprintf('\nEnter your calibration measurements:\n');
        calib_sys = input('  Calibration systolic BP (mmHg): ');
        calib_dia = input('  Calibration diastolic BP (mmHg): ');
        calib_ptt_ms = input('  Calibration PTT (ms): ');
        
        % Validate calibration inputs
        if isempty(calib_sys) || isempty(calib_dia) || isempty(calib_ptt_ms)
            fprintf('Warning: Invalid calibration values. Using population defaults.\n');
            calib_sys = DEFAULT_SYS;
            calib_dia = DEFAULT_DIA;
            calib_ptt_ms = DEFAULT_PTT_MS;
            using_defaults = true;
        else
            using_defaults = false;
        end
    else
        calib_sys = DEFAULT_SYS;
        calib_dia = DEFAULT_DIA;
        calib_ptt_ms = DEFAULT_PTT_MS;
        using_defaults = true;
        fprintf('\nUsing population default calibration:\n');
        fprintf('  Systolic BP:  %d mmHg\n', calib_sys);
        fprintf('  Diastolic BP: %d mmHg\n', calib_dia);
        fprintf('  PTT:          %.0f ms\n', calib_ptt_ms);
    end
    
    fprintf('\n');
    
    %% Step 3: Additional Features (optional)
    fprintf('--- STEP 3: Additional Features (Optional) ---\n');
    fprintf('The model uses 4 features. delta_ptt is computed from your PTT input.\n');
    fprintf('You can optionally provide the other 3 features for better accuracy.\n\n');
    
    has_features = input('Do you have additional feature values? (Y/N): ', 's');
    
    if strcmpi(has_features, 'Y')
        fprintf('\nEnter additional feature values (press Enter to use default 0):\n');
        fprintf('  delta_hr: Heart rate change from calibration (bpm)\n');
        delta_hr_input = input('  delta_hr (default 0): ');
        if isempty(delta_hr_input) || ~isnumeric(delta_hr_input)
            delta_hr = 0;
        else
            delta_hr = delta_hr_input;
        end
        
        fprintf('  ptt_iqr: PTT interquartile range (samples) - measures PTT variability\n');
        ptt_iqr_input = input('  ptt_iqr (default 0): ');
        if isempty(ptt_iqr_input) || ~isnumeric(ptt_iqr_input)
            ptt_iqr = 0;
        else
            ptt_iqr = ptt_iqr_input;
        end
        
        fprintf('  cv_ptt: Coefficient of variation (std/mean) - unitless\n');
        cv_ptt_input = input('  cv_ptt (default 0): ');
        if isempty(cv_ptt_input) || ~isnumeric(cv_ptt_input)
            cv_ptt = 0;
        else
            cv_ptt = cv_ptt_input;
        end
        
        using_advanced = true;
    else
        delta_hr = 0;
        ptt_iqr = 0;
        cv_ptt = 0;
        using_advanced = false;
        fprintf('Using default values: delta_hr=0, ptt_iqr=0, cv_ptt=0\n');
    end
    
    fprintf('\n');
    
    %% Step 4: Calculate Prediction (SAME as target_3)
    fprintf('--- STEP 4: Prediction ---\n\n');
    
    % Convert PTT from ms to samples for coefficient application
    ptt_samples = ptt_ms / 1000 * FS;
    calib_ptt_samples = calib_ptt_ms / 1000 * FS;
    
    % Compute delta_ptt feature
    delta_ptt = ptt_samples - calib_ptt_samples;
    delta_ptt_ms = ptt_ms - calib_ptt_ms;
    
    % Apply FULL model (same prediction formula as target_3)
    % delta_BP = intercept + coef_delta_ptt*delta_ptt + coef_delta_hr*delta_hr 
    %                      + coef_ptt_iqr*ptt_iqr + coef_cv_ptt*cv_ptt
    delta_sys = sys_intercept + sys_coef_delta_ptt*delta_ptt + sys_coef_delta_hr*delta_hr ...
                              + sys_coef_ptt_iqr*ptt_iqr + sys_coef_cv_ptt*cv_ptt;
    delta_dia = dia_intercept + dia_coef_delta_ptt*delta_ptt + dia_coef_delta_hr*delta_hr ...
                              + dia_coef_ptt_iqr*ptt_iqr + dia_coef_cv_ptt*cv_ptt;
    
    pred_sys = calib_sys + delta_sys;
    pred_dia = calib_dia + delta_dia;
    
    % Display calculation details
    fprintf('Feature values (same features as target_3):\n');
    fprintf('  delta_ptt = %.2f samples (%.1f ms change from calibration)\n', delta_ptt, delta_ptt_ms);
    fprintf('  delta_hr  = %.2f bpm (default: 0 for single PTT)\n', delta_hr);
    fprintf('  ptt_iqr   = %.2f samples (default: 0 for single PTT)\n', ptt_iqr);
    fprintf('  cv_ptt    = %.4f (default: 0 for single PTT)\n', cv_ptt);
    fprintf('\n');
    
    fprintf('Model calculation:\n');
    fprintf('  delta_sys = %.4f + %.4f*%.2f + %.4f*%.2f + %.4f*%.2f + %.4f*%.4f\n', ...
            sys_intercept, sys_coef_delta_ptt, delta_ptt, sys_coef_delta_hr, delta_hr, ...
            sys_coef_ptt_iqr, ptt_iqr, sys_coef_cv_ptt, cv_ptt);
    fprintf('           = %.2f mmHg\n', delta_sys);
    fprintf('  delta_dia = %.4f + %.4f*%.2f + %.4f*%.2f + %.4f*%.2f + %.4f*%.4f\n', ...
            dia_intercept, dia_coef_delta_ptt, delta_ptt, dia_coef_delta_hr, delta_hr, ...
            dia_coef_ptt_iqr, ptt_iqr, dia_coef_cv_ptt, cv_ptt);
    fprintf('           = %.2f mmHg\n', delta_dia);
    fprintf('\n');
    
    %% Step 5: Display Results
    fprintf('============================================================\n');
    fprintf('PREDICTED BLOOD PRESSURE\n');
    fprintf('============================================================\n\n');
    
    fprintf('  Systolic:  %.0f mmHg (calibration %d + delta %.1f)\n', round(pred_sys), calib_sys, delta_sys);
    fprintf('  Diastolic: %.0f mmHg (calibration %d + delta %.1f)\n', round(pred_dia), calib_dia, delta_dia);
    fprintf('\n');
    
    % BP category
    fprintf('BP Category: ');
    if pred_sys < 120 && pred_dia < 80
        fprintf('Normal\n');
    elseif pred_sys < 130 && pred_dia < 80
        fprintf('Elevated\n');
    elseif pred_sys < 140 || pred_dia < 90
        fprintf('High Blood Pressure Stage 1\n');
    elseif pred_sys < 180 || pred_dia < 120
        fprintf('High Blood Pressure Stage 2\n');
    else
        fprintf('Hypertensive Crisis - Seek Medical Attention!\n');
    end
    
    fprintf('\n');
    
    % Accuracy note
    if using_defaults
        fprintf('Note: Prediction uses population defaults.\n');
        fprintf('      For better accuracy, provide your own calibration values.\n');
    else
        fprintf('Note: Prediction based on your calibration values.\n');
    end
    fprintf('\n');
    fprintf('Note: This uses the SAME model as target_3_predictive_model.m\n');
    fprintf('      Features delta_hr, ptt_iqr, cv_ptt default to 0 for single PTT input.\n');
    
end


%% Helper Function: Extract metric value from table
function value = get_metric(metrics_table, metric_name)
    % Extract a metric value from the model_metrics.csv table.
    %
    % Args:
    %     metrics_table: Table loaded from model_metrics.csv
    %     metric_name: Name of the metric to extract
    %
    % Returns:
    %     value: Numeric value of the metric, or NaN if not found
    
    if iscell(metrics_table.metric)
        mask = strcmp(metrics_table.metric, metric_name);
    else
        mask = (metrics_table.metric == metric_name);
    end
    
    if any(mask)
        val = metrics_table.value(mask);
        if iscell(val)
            value = str2double(val{1});
        elseif isstring(val) || ischar(val)
            value = str2double(val);
        else
            value = val;
        end
    else
        value = NaN;
    end
end
